# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    # ur_right_joint_group_pos_controller:
    #   type: position_controllers/JointGroupPositionController

    # ur_left_joint_group_pos_controller:
    #   type: position_controllers/JointGroupPositionController

    ur_left_joint_group_vel_controller:
      type: velocity_controllers/JointGroupVelocityController

    # ur_right_joint_group_pos_controller:
    #   type: position_controllers/JointGroupPositionController

    # ur_right_joint_group_vel_controller:
    #   type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


# # ur_right_joint_group_pos_controller:
# #   ros__parameters:
# #     joints:
# #       - ur_right_shoulder_pan_joint
# #       - ur_right_shoulder_lift_joint
# #       - ur_right_elbow_joint
# #       - ur_right_wrist_1_joint
# #       - ur_right_wrist_2_joint
# #       - ur_right_wrist_3_joint

# # ur_right_joint_group_vel_controller:
# #   ros__parameters:
# #     joints:
# #       - ur_right_shoulder_pan_joint
# #       - ur_right_shoulder_lift_joint
# #       - ur_right_elbow_joint
# #       - ur_right_wrist_1_joint
# #       - ur_right_wrist_2_joint
# #       - ur_right_wrist_3_joint

# #     pid_gains:
# #       ur_right_shoulder_pan_joint: {p: 100000.0, i: 0.01, d: 10.0}
# #       ur_right_shoulder_lift_joint: {p: 10000.0, i: 0.01, d: 10.0}
# #       ur_right_elbow_joint: {p: 10000.0, i: 0.01, d: 10.0}
# #       ur_right_wrist_1_joint: {p: 100.0, i: 0.01, d: 10.0}
# #       ur_right_wrist_2_joint: {p: 100.0, i: 0.01, d: 10.0}
# #       ur_right_wrist_3_joint: {p: 100.0, i: 0.01, d: 10.0}
 
# #     interface_name: velocity


# # ur_left_joint_group_pos_controller:
# #   ros__parameters:
# #     joints:
# #       - ur_left_shoulder_pan_joint
# #       - ur_left_shoulder_lift_joint
# #       - ur_left_elbow_joint
# #       - ur_left_wrist_1_joint
# #       - ur_left_wrist_2_joint
# #       - ur_left_wrist_3_joint

ur_left_joint_group_vel_controller:
  ros__parameters:
    joints:
      - ur_left_shoulder_pan_joint
      - ur_left_shoulder_lift_joint
      - ur_left_elbow_joint
      - ur_left_wrist_1_joint
      - ur_left_wrist_2_joint
      - ur_left_wrist_3_joint

    pid_gains:
      ur_left_shoulder_pan_joint: {p: 10.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_left_shoulder_lift_joint: {p: 10.0,  i: .05, d: 0.1, i_clamp: 1}
      ur_left_elbow_joint: {p: 10.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_left_wrist_1_joint: {p: 10.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_left_wrist_2_joint: {p: 10.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur_left_wrist_3_joint: {p: 10.0,  i: 0.05, d: 0.1, i_clamp: 1}
 
    interface_name: velocity

    
