# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ur_left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    ur_left_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ur_left_arm_controller:
  ros__parameters:
    joints:
      - ur_left_shoulder_pan_joint
      - ur_left_shoulder_lift_joint
      - ur_left_elbow_joint
      - ur_left_wrist_1_joint
      - ur_left_wrist_2_joint
      - ur_left_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
ur_left_hand_controller:
  ros__parameters:
    joints:
      - ur_left_bl_to_leftFinger
      - ur_left_leftFinger_to_rightFinger
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity