# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ur_left_arm_controller
    - ur_right_arm_controller

  ur_left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - ur_left_shoulder_pan_joint
      - ur_left_shoulder_lift_joint
      - ur_left_elbow_joint
      - ur_left_wrist_1_joint
      - ur_left_wrist_2_joint
      - ur_left_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
  ur_right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - ur_right_shoulder_pan_joint
      - ur_right_shoulder_lift_joint
      - ur_right_elbow_joint
      - ur_right_wrist_1_joint
      - ur_right_wrist_2_joint
      - ur_right_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true